### ISSUE TITLE
US1.1:En tant qu'utilisateur, j'aimerais avoir une page d'accueil qui présente le produit

### ISSUE THREAD

**Issue by PirLucas** [a-kalin0/Cat-In-Cat-Out#1]
Difficulté: facile
Sprint début: 1
Sprint fin: 2
Nb heures estimées: 3h
Nb heures réels: 4h

# Description, intérêt et objectif

L'utilisateur doit arriver sur le site page une page accueillante, qui présente le produit de CICO. La page possède un menu qui permet de naviguer dans le reste du site. Un onglet faq, un onglet contact, un onglet connexion, un onglet permettant de retourner a l'accueill.
La page possède également un lien permettant de commander le produit

# Critères d'acceptation

La page est la première page sur laquelle un utilisateur tombe
La page montre le titre et logo du projet
On y trouve un onglet redirigeant vers la page FAQ
On y trouve un onglet redirigeant vers la page contacts
On y trouve un onglet redirigeant vers la page de connexion
On y trouve un onglet redirigeant vers la page d'accueil
Ces onglets sont dans une bande réutilisable et réutilisée par les autres pages du menu
La page possède un texte de description du produit
La page possède un lien vers une page de commande

# Maquette

![Image](https://github.com/a-kalin0/Cat-In-Cat-Out/assets/93054207/b33212df-7679-4b0a-bca1-48047ac98e2c)

# Prérequis

Avoir un frontend fonctionnel

# Utilisation de la db

Aucune modification de la DB

# Taches Techniques

-afficher de l'html depuis le serveur
-créer des liens de redirection:
   -Vers la page d'accueil
   -Vers la page de FAQ
   -Vers la page de connexion
   -Vers la page de contacts
-Mettre ces liens dans une même section de code, qui pourra être réutilisée tel quel dans les autres pages
-Afficher un texte de présentation
-Mettre un bouton redirigeant vers la page de commande

-Peaufiner l'affichage

**Comment by iglesias1602** [comment]
@o-kinnen Est-ce qu'il y a moyen de concevoir des maquettes avec @Fire-Aspect du module ? Comme ça, je pourrai déjà les mettre comme exemple dans la page d'accueil.

**Comment by o-kinnen** [comment]
Je vais voir avec lui
