### ISSUE TITLE
US1.2 En tant qu'utilisateur, j'aimerais avoir une page FAQ (frequently asked questions)

### ISSUE THREAD

**Issue by PirLucas** [a-kalin0/Cat-In-Cat-Out#3]
Difficulté: vraiment facile
sprint debut: 2
sprint fin:
nb heures estimées: 1h
nb heures reeles:

# Description, intérêt et objectif

La page doit permettre à l'utilisateur de trouver les réponses à ses questions, les réponses sont organisées sous forme de liste etendable

# Critères d'acceptation

On y trouve le meme header que la page d'acceuil
On y trouve une liste de question fréquement posées
les question sont présentées par des liste déroulantes

# Maquette

![Image](https://github.com/a-kalin0/Cat-In-Cat-Out/assets/93054207/abcccb6e-f041-4022-8568-db142ed054ee)

# Prérequis

Avoir un frontend fonctionnel
Avoir le header de liens de l'US1.1

# Utilisation de la db

Aucune modification de la DB

# Taches Techniques

-afficher de l'html depuis le serveur
-inserer le header de liens
-creer des listes déroulantes
-remplir les liste déroulates de question et leurs réponses

-Peaufiner l'affichage

**Comment by iglesias1602** [comment]
Le design de la page FAQ c'est déjà fait. Faut regarder ma pull request #9 .
Il faut encore ajouter des questions (?) Faudra trouver un public pour expliquer notre projet et puis les questions qu'ils poseront on pourra les ajouter dans la page FAQ peut-être ?
