### ISSUE TITLE
US1.3: En tant qu'utilisateur, j'aimerais avoir une page de contact

### ISSUE THREAD

**Issue by PirLucas** [a-kalin0/Cat-In-Cat-Out#4]
Difficulté: vraiment facile
sprint debut: 2
sprint fin:
nb heures estimées: 1h
nb heures reeles:

# Description, intérêt et objectif

La page doit permettre à l'utilisateur de trouver les liens de contacts importants, tels que numéro de téléphone, mail, localisation.
La localisation est affichée avec une carte.

# Critères d'acceptation

On y trouve le meme header que la page d'acceuil
On y trouve un numéro de téléphone
On y trouve une adresse
On y trouve un mail
On y vois une localisation avec une carte

# Maquette

![Image](https://github.com/a-kalin0/Cat-In-Cat-Out/assets/93054207/e7fcec12-daef-4d15-87c0-9584a88c6519)

# Prérequis

Avoir un frontend fonctionnel
Avoir le header de liens de l'US1.1

# Utilisation de la db

Aucune modification de la DB

# Taches Techniques

-afficher de l'html depuis le serveur
-inserer le header de liens
-écrire les différents contacts
-Faire un mien avec maps et y afficher l'adresse

-Peaufiner l'affichage

**Comment by iglesias1602** [comment]
@PirLucas la page de contact est faite. faut regarde ma branche dev_Carlos. J'ai fait un lien dans l'onglet "Development".

S'il y a des modifications à faire faut me prévenir.

**Comment by PirLucas** [comment]
L'onglet "development"? Celui qui est en bas de la page? rien ne se passe quand je clique dessus

**Comment by iglesias1602** [comment]
C'est bizarre  normalement j'ai lié la branché. Je t'envoie une capture d'écran.

![image](https://github.com/a-kalin0/Cat-In-Cat-Out/assets/92795126/cb77e0a7-e7c1-4295-8e60-5551c46bd7c7)

**Comment by PirLucas** [comment]
aahhh, je pensais que tu parlais du lien "devlopment" sur le site XD

**Comment by iglesias1602** [comment]
AH non pas du tout XD, j'ai découvert qu'on peut lier des branches à des issues directement. Mais c'est plus simple quand il y a une pull request.
