### ISSUE TITLE
US1.4: En tant qu'utilisateur, j'aimerais avoir une page de connexion

### ISSUE THREAD

**Issue by PirLucas** [a-kalin0/Cat-In-Cat-Out#5]
Difficulté: facile
sprint debut: 1
sprint fin:
nb heures estimées: 3h
nb heures réelles:

# Description, intérêt et objectif

L'utilisateur doit pouvoir soit créer un compte, soit se connecter. Il se connecte avec son mail et son mot de passe.
Il crée un compte avec un mail, nom, prénom, mot de passe deux fois, et le numéro de série de son accessoire

# Critères d'acceptation

La page donne l'option de créer un compte ou de se connecter
Dans le cas ou on se connecte, il y a un formulaire demandant adresse mail et mot de passe
la page averti si la connexion à échouée
Si on veux créer un compte, il y a un formulaire demandant mail, nom, prénom, mot de passe deux fois, et le numéro de série de son accessoire

# Maquette

![Image](https://github.com/a-kalin0/Cat-In-Cat-Out/assets/93054207/ae2537e1-98da-443f-a3b3-c61a77e9d9ba)

# Prérequis

Avoir un frontend fonctionnel
Avoir un lien fonctionnel avec la db

# Utilisation de la db

Acces en lecture à la DB en cas de connexion
Acces en écriture à la db en cas de création de compte

# Taches Techniques

-afficher de l'html depuis le serveur
-creer un formulaire de connexion
-creer un formulaire de création de compte
-creer un bouton pour creer un compte
-creer le bouton de validation

-Peaufiner l'affichage

**Comment by iglesias1602** [comment]
La page de connexion se trouve déjà dans la branche dev_Carlos (elle a été liée en haut dans l'onglet 'development').
