### ISSUE TITLE
US1.4.1: En that qu'utilisatieur, je veux pouvoir creer un compte

### ISSUE THREAD

**Issue by PirLucas** [a-kalin0/Cat-In-Cat-Out#8]
Difficulté: facile
sprint debut: 2
sprint fin: 2
nb heures estimées: 2h
nb heures reeles: 3h

# Description, intérêt et objectif

L'utilisateur doit pouvoir creer un compte s'in n'en a pas un, il doit renseigner son aresse mail, nom utilisateur, son mot de passe duex fois et le numéro de série de son accessoire. La création de comtpe est refusée si l'adresse mail est déjà utilisée, si le numéro de série n'es pas valide, si le mot de passe ne correspond pas a la confirmation

# Critères d'acceptation

L'utilisateur à acces a un formulaire de creation de compte
Le formulaire demande:
-l'identifiant
-l'adresse mail
-le mot de pase
-confirmation du mot de passe

la création echoue quand l'adresse existe déjà dans la db
...quand la confiration du mot de passe ne correspond pas au mot de passe
un message de refus apparait quand la création de compte échoue

Un fois le compte créé, on peut se connecter immédiatement

# Maquette

![Image](https://github.com/a-kalin0/Cat-In-Cat-Out/assets/93054207/ae2537e1-98da-443f-a3b3-c61a77e9d9ba)

# Prérequis

Avoir un frontend fonctionnel
Avoir un lien fonctionnel avec la db

# Utilisation de la db

Acces en lecture et en écriture sur la DB
Une nouvelle entrée dans la table CICO_usercico est crée

# Taches Techniques

-creer le systeme d'authentification
-creer un formulaire de création de compte
-creer les différentes vérifications

-Peaufiner l'affichage

**Comment by a-kalin0** [comment]
Fais gaffe au titre de l'US (orthographe), 
Quand on clique sur "créer un compte", on arrive sur le formulaire d'inscription MAIS en haut du formulaire on a "se connecter" ==> ça porte à confusion

**Comment by PirLucas** [comment]
Cela a été corrigé
